language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: brannanh-github
    token:
      secure: bb0b4c628cace31225cc3f0087f6e81f9d637ac8
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'